/**
 * Bootstraps the native iOS project after a fresh clone.
 *
 * Background: the Xcode project (App.xcodeproj, Podfile, Info.plist,
 * AppDelegate.swift) is generated by Capacitor and is not in git. A handful of
 * BeenBy-specific files under ios/ ARE in git (LaunchScreen.storyboard, the
 * app icon set, the cordova plugin stubs). Because ios/ therefore already
 * exists in a fresh clone, plain `npx cap add ios` aborts with
 * "ios platform already exists".
 *
 * This script does the safe dance:
 *   1. If App.xcodeproj already exists -> do nothing (idempotent).
 *   2. Back up every git-tracked file under ios/ to a temp folder.
 *   3. Remove ios/ and let Capacitor generate a clean native project.
 *   4. Restore the tracked files on top of the generated project.
 *
 * Nothing BeenBy-specific is lost: the custom plugins live in
 * capacitor-plugins/ (linked by `cap sync`), and Info.plist strings,
 * localizations, entitlements/push capability and the app icon are re-applied
 * by the patch scripts that `npm run ios:sync` runs afterwards.
 *
 * Run: node scripts/init-ios.mjs   (npm run ios:init)
 */
import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

const IOS_DIR = "ios";
const XCODEPROJ = "ios/App/App.xcodeproj";
const PODFILE = "ios/App/Podfile";

/** Files we always keep even if git is unavailable (e.g. a downloaded zip). */
const FALLBACK_PRESERVE = [
  "ios/App/App/Base.lproj/LaunchScreen.storyboard",
  "ios/App/App/Assets.xcassets",
  "ios/capacitor-cordova-ios-plugins",
  "ios/README.md",
];

function run(cmd, args) {
  execFileSync(cmd, args, { stdio: "inherit" });
}

/* ---------- 1. already initialised? ---------- */
if (existsSync(XCODEPROJ) && existsSync(PODFILE)) {
  console.log(
    "iOS-projektet finns redan (ios/App/App.xcodeproj + Podfile). Inget att göra — kör `npm run ios:sync`.",
  );
  process.exit(0);
}

/* ---------- 2. back up tracked files ---------- */
let preserve = [];
try {
  preserve = execFileSync("git", ["ls-files", IOS_DIR], { encoding: "utf8" })
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
} catch {
  preserve = [];
}
if (!preserve.length) {
  preserve = FALLBACK_PRESERVE.filter((p) => existsSync(p));
}

const backupDir = mkdtempSync(join(tmpdir(), "beenby-ios-"));
let backedUp = 0;
for (const rel of preserve) {
  if (!existsSync(rel)) continue;
  const dest = join(backupDir, rel);
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(rel, dest, { recursive: true });
  backedUp += 1;
}
console.log(`Sparade ${backedUp} spårade iOS-filer tillfälligt.`);

/* ---------- 3. regenerate the native project ---------- */
if (existsSync(IOS_DIR)) {
  rmSync(IOS_DIR, { recursive: true, force: true });
}

const capAdd = process.env["BEENBY_CAP_ADD"];
try {
  if (capAdd) {
    run("sh", ["-c", capAdd]);
  } else {
    run("npx", ["cap", "add", "ios"]);
  }
} catch (error) {
  // Put the tracked files back so the working tree is never left damaged.
  for (const rel of preserve) {
    const src = join(backupDir, rel);
    if (!existsSync(src)) continue;
    mkdirSync(dirname(rel), { recursive: true });
    cpSync(src, rel, { recursive: true });
  }
  rmSync(backupDir, { recursive: true, force: true });
  console.error(
    "\n`npx cap add ios` misslyckades. Dina spårade iOS-filer är återställda.\n" +
      "Kontrollera att du kör på macOS med Xcode och CocoaPods installerat.",
  );
  throw error;
}

/* ---------- 4. restore tracked files on top ---------- */
let restored = 0;
for (const rel of preserve) {
  const src = join(backupDir, rel);
  if (!existsSync(src)) continue;
  mkdirSync(dirname(rel), { recursive: true });
  cpSync(src, rel, { recursive: true, force: true });
  restored += 1;
}
rmSync(backupDir, { recursive: true, force: true });

console.log(
  `Återställde ${restored} BeenBy-filer (launch screen, appikoner, cordova-stubbar).\n` +
    "Klart. Kör nu: npm run ios:sync",
);
