/**
 * Ensures the native Android project exists. The Android project IS committed
 * (android/), so on a normal clone this does nothing. If android/ is missing it
 * is generated by Capacitor. iOS files are never touched.
 *
 * Run: npm run android:init
 */
import { execSync } from "node:child_process";
import { existsSync } from "node:fs";

if (existsSync("android/app/build.gradle")) {
  console.log("[android:init] android/ already present — nothing to do.");
} else {
  execSync("npx cap add android", { stdio: "inherit" });
  console.log("[android:init] Android project created. Review android/app/src/main/AndroidManifest.xml.");
}
