/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as StartAdressRouteImport } from './routes/start.adress'
import { Route as StartVemRouteImport } from './routes/start.vem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAdressRoute = StartAdressRouteImport.update({
  id: '/start/adress',
  path: '/start/adress',
  getParentRoute: () => rootRouteImport,
} as any)
const StartVemRoute = StartVemRouteImport.update({
  id: '/start/vem',
  path: '/start/vem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/join/$token' | '/start/adress' | '/start/vem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/join/$token' | '/start/adress' | '/start/vem'
  id:
    '__root__' | '/' | '/chat' | '/join/$token' | '/start/adress' | '/start/vem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  JoinTokenRoute: typeof JoinTokenRoute
  StartAdressRoute: typeof StartAdressRoute
  StartVemRoute: typeof StartVemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/adress': {
      id: '/start/adress'
      path: '/start/adress'
      fullPath: '/start/adress'
      preLoaderRoute: typeof StartAdressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/vem': {
      id: '/start/vem'
      path: '/start/vem'
      fullPath: '/start/vem'
      preLoaderRoute: typeof StartVemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  JoinTokenRoute: JoinTokenRoute,
  StartAdressRoute: StartAdressRoute,
  StartVemRoute: StartVemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
