/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as StartAdressRouteImport } from './routes/start.adress'
import { Route as StartFargRouteImport } from './routes/start.farg'
import { Route as StartKodRouteImport } from './routes/start.kod'
import { Route as StartValkommenRouteImport } from './routes/start.valkommen'
import { Route as StartVemRouteImport } from './routes/start.vem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAdressRoute = StartAdressRouteImport.update({
  id: '/start/adress',
  path: '/start/adress',
  getParentRoute: () => rootRouteImport,
} as any)
const StartFargRoute = StartFargRouteImport.update({
  id: '/start/farg',
  path: '/start/farg',
  getParentRoute: () => rootRouteImport,
} as any)
const StartKodRoute = StartKodRouteImport.update({
  id: '/start/kod',
  path: '/start/kod',
  getParentRoute: () => rootRouteImport,
} as any)
const StartValkommenRoute = StartValkommenRouteImport.update({
  id: '/start/valkommen',
  path: '/start/valkommen',
  getParentRoute: () => rootRouteImport,
} as any)
const StartVemRoute = StartVemRouteImport.update({
  id: '/start/vem',
  path: '/start/vem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/farg': typeof StartFargRoute
  '/start/kod': typeof StartKodRoute
  '/start/valkommen': typeof StartValkommenRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/farg': typeof StartFargRoute
  '/start/kod': typeof StartKodRoute
  '/start/valkommen': typeof StartValkommenRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/adress': typeof StartAdressRoute
  '/start/farg': typeof StartFargRoute
  '/start/kod': typeof StartKodRoute
  '/start/valkommen': typeof StartValkommenRoute
  '/start/vem': typeof StartVemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/join/$token'
    | '/start/adress'
    | '/start/farg'
    | '/start/kod'
    | '/start/valkommen'
    | '/start/vem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/join/$token'
    | '/start/adress'
    | '/start/farg'
    | '/start/kod'
    | '/start/valkommen'
    | '/start/vem'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/join/$token'
    | '/start/adress'
    | '/start/farg'
    | '/start/kod'
    | '/start/valkommen'
    | '/start/vem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  JoinTokenRoute: typeof JoinTokenRoute
  StartAdressRoute: typeof StartAdressRoute
  StartFargRoute: typeof StartFargRoute
  StartKodRoute: typeof StartKodRoute
  StartValkommenRoute: typeof StartValkommenRoute
  StartVemRoute: typeof StartVemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/adress': {
      id: '/start/adress'
      path: '/start/adress'
      fullPath: '/start/adress'
      preLoaderRoute: typeof StartAdressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/farg': {
      id: '/start/farg'
      path: '/start/farg'
      fullPath: '/start/farg'
      preLoaderRoute: typeof StartFargRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/kod': {
      id: '/start/kod'
      path: '/start/kod'
      fullPath: '/start/kod'
      preLoaderRoute: typeof StartKodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/valkommen': {
      id: '/start/valkommen'
      path: '/start/valkommen'
      fullPath: '/start/valkommen'
      preLoaderRoute: typeof StartValkommenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/vem': {
      id: '/start/vem'
      path: '/start/vem'
      fullPath: '/start/vem'
      preLoaderRoute: typeof StartVemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  JoinTokenRoute: JoinTokenRoute,
  StartAdressRoute: StartAdressRoute,
  StartFargRoute: StartFargRoute,
  StartKodRoute: StartKodRoute,
  StartValkommenRoute: StartValkommenRoute,
  StartVemRoute: StartVemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
